name: abr_analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy>=1.21.0
  - scipy>=1.7.0
  - matplotlib>=3.5.0
  - mne>=1.0.0
  - expyfun>=0.8.0
  - pip
  - pip:
    - h5py>=3.7.0
    - pathlib
    - typing-extensions 